### ISSUE TITLE
リクルートページを削除

### ISSUE THREAD

**Issue by ayumitk** [yukisato/compass-canada-school#13]
https://canada-school.com/recruit2/
https://canada-school.com/forum/forum/recruit/

先方から、このページも使っていないから削除して欲しいとのこと。

@yukisato  [bbPress](https://wordpress.org/plugins/bbpress/) というプラグインを使用して作っているページ。
Wordpress の sato アカウントにbbPressの権限がないため、対応が難しいです。
先方に権限を付与してもらってください。

**Comment by yukisato** [comment]
こちらも了解です！
