### ISSUE TITLE
トップページのワイヤーフレームを作成

### ISSUE THREAD

**Issue by ayumitk** [yukisato/compass-canada-school#15]
@yukisato Ver. 3を作成しました。

- 私たちについて
- サービスについて

2箇所の内容を埋めましたので、先方に確認をお願いいたします。
https://xd.adobe.com/view/b8483f35-cfc6-4c6d-8f44-cd3e26bf2ea5-ed1b/screen/f3bce892-30c3-49de-974d-20228989a179/

この内容で作り始めておきますので、変更等は随時送ってください。

**Comment by ayumitk** [comment]
先方より、
- スタッフ写真は再度撮影する予定
- それ以外の写真はこちらで用意する

**Comment by yukisato** [comment]
先方の写真は今月29日撮影予定とのこと。
撮る人は僕の知り合いを紹介する予定だけど、ダメだったら他の人になると思う。

**Comment by ayumitk** [comment]
トップページデザイン共有用URL:
https://xd.adobe.com/view/424f5fb2-111b-4bb3-ab0d-53f4b0ea47d1-171c/

※もう一段階仕上げてから先方に提出予定。今夜いけるはず

**Comment by ayumitk** [comment]
#33 本デザインに入ったのでクローズ
