### ISSUE TITLE
カナダ完全ガイド統合の本番化作業

### ISSUE THREAD

**Issue by yukisato** [yukisato/compass-canada-school#19]
カナダ完全ガイドをブログに統合 #4 の本番反映作業のチェックリスト。

## 懸念事項
`.gitignore` での `plugin/` ディレクトリの除外をしたので、masterブランチ反映時にプラグインが消えてしまう可能性があり、
作業時に本番のプラグインディレクトリのバックアップと、masterの更新後のプラグインの復旧が必用。

All-in-one Migrationプラグインのバージョンが古くないとリストアが出来ない可能性があるので

以下の手順で反映を行う。

- [x] All-in-one Migrationプラグインの旧バージョンを用意しておく（リストアモードが動かなかった時用）
- [x] 本番サイトのプラグインディレクトリをバックアップ
- [x] 本番サイトのAll in oneマイグレーションで全てを含めたバックアップを作成
- [x] staging->master へのマージ（プルリク）
- [x] 本番サーバーで master を pull ⇢動作確認
- [x] サイトの表示を確認。問題が会った場合はAll-in-one Migrationで全体をリストア
- [x] wp-adminのプラグインをチェック。プラグインに問題があった場合はプラグインのバックアップをリストア

サイトに問題がなくプラグインのみ消えた状態からプラグインの復旧をした場合は問題ないのでリリース完了とする（恐らくこの可能性が一番高い）

**Comment by ayumitk** [comment]
外部へのリンク切れ、先方作業お願いします
https://canada-school.com/wp-admin/tools.php?page=view-broken-links

**Comment by ayumitk** [comment]
リンク切れリスト
[リンクチェック.txt](https://github.com/yukisato/compass-canada-school/files/5222657/default.txt)

**Comment by ayumitk** [comment]
本番反映したのでクローズ
