### ISSUE TITLE
ブログのフッターに関連記事を追加

### ISSUE THREAD

**Issue by ayumitk** [yukisato/compass-canada-school#2]
- 表示件数は3件
- 2件は、Simple GA Rankingプラグインの上位から取得
- 1件は、同カテゴリ内での新着記事
- 表示中の記事にカテゴリが複数設定してある場合は、メインに設定されているカテゴリを使用

**Comment by ayumitk** [comment]
@yukisato 今、SNS「この記事が気に入ったらいいね ! しよう」の下に関連記事が出るようになってるけど、上下入れ替えた方がいいかも？入れ替えは可能なので、ちょっと先方やブロガーさんの意見をお聞きしたいところです

![【8-27更新】カナダの新型コロナウイルスに関する最新情報・ニュースまとめ-カナダ留学コンパス](https://user-images.githubusercontent.com/33358068/91930175-fcdedb80-ec94-11ea-8871-4aa5a235fc14.png)

**Comment by yukisato** [comment]
@ayumitk 
メモ
末永さんと話した結果、「スッキリするほうで」とのこと。
SNS「この記事が気に入ったらいいね ! しよう」の位置の件については今回はノータッチということになった。

**Comment by ayumitk** [comment]
#19 公開作業が終わったのでクローズ
