### ISSUE TITLE
リダイレクトの正規表現

### ISSUE THREAD

**Issue by ayumitk** [yukisato/compass-canada-school#21]
カナダ完全ガイドの各記事
- /canada/miku-interview/　→　/miku-interview/
- /canada/host-hostess/　→　/host-hostess/

カナダ完全ガイドのindex
- /canada/　→　/category/canada/

正規表現で書くとどう書けば？
カテゴリ一覧ページ（https://staging.canada-school.com/category/canada/info/）にも `/canada/` が出てくるので

**Comment by yukisato** [comment]
カナダ完全ガイドの各記事

## 全ての/canada/以下をルート直下にリダイレクト

マッチ
```
^canada/(.*)$
```
※マッチしなかった場合は `^/canada/(.*)$`  というようにcanadaの前にスラッシュをつけて試して下さい。

変換先
```
/\1
```

## カナダ完全ガイドのindex
マッチ
```
^canada/$
```

変換先
```
category/canada/
```

カナダ完全ガイドを先にRewrite反映する必用があります。

**Comment by ayumitk** [comment]
うーん、どうも、プラグインが全ての正規表現に対応してないかも
https://staging.canada-school.com/wp-admin/tools.php?page=redirection.php

難しそうなら、.htaccess でやってもらったがいいかも

**Comment by ayumitk** [comment]
プラグイン Redirection で問題なくリダイレクトされたので、クローズします
