### ISSUE TITLE
ページングのリンク先が違う

### ISSUE THREAD

**Issue by yukisato** [yukisato/compass-canada-school#67]
末永さんからの問い合わせですが、スマホからのみ、ページングをクリックするとトップページに飛んでしまうようです。

ご確認をお願いします。

![S__47415313](https://user-images.githubusercontent.com/23222989/95927762-88f42080-0d74-11eb-8422-a500a56a677c.jpg)

**Comment by ayumitk** [comment]
### 原因

リダイレクト設定
https://canada-school.com/wp-admin/tools.php?page=redirection.php

```
^/canada/(.+)$
/$1
```

ページネーションのリンク先が ```/canada/page/2/``` なので、リダイレクト設定により ```/canada/``` が外されてしまう

**Comment by ayumitk** [comment]
本番のリダイレクト設定を調整したのでクローズ
